---
title: "PX-Web API, osa 5"
author: "Henri Linnanketo"
date: "2024-08-04"
output:
  html_document: default
  word_document: default
editor_options: 
  chunk_output_type: inline
---

```{r include=FALSE}
# Ladataan paketit.

library(pxweb)
library(dplyr)
library(tidyr)

# Tehdään kysely.

kysely <- list("Alue"=c('0910000000',
                        '0911000000',
                        '0911101000',
                        '0911101010',
                        '0911101020',
                        '0911101080',
                        '0911102000',
                        '0911102030',
                        '0911102050',
                        '0911102060',
                        '0911102070',
                        '0911102090',
                        '0911102204',
                        '0911102520',
                        '0911103000',
                        '0911103040',
                        '0911103130',
                        '0911103201',
                        '0911103202',
                        '0911103203',
                        '0911104000',
                        '0911104140',
                        '0911105000',
                        '0911105311',
                        '0911105312',
                        '0911105313',
                        '0912000000',
                        '0912201000',
                        '0912201150',
                        '0912201161',
                        '0912201162',
                        '0912201180',
                        '0912202000',
                        '0912202301',
                        '0912202302',
                        '0912202303',
                        '0912202304',
                        '0912202305',
                        '0912202306',
                        '0912203000',
                        '0912203291',
                        '0912203292',
                        '0912203293',
                        '0912203294',
                        '0912204000',
                        '0912204320',
                        '0912204461',
                        '0912204462',
                        '0912204463',
                        '0912204464',
                        '0912204465',
                        '0912205000',
                        '0912205331',
                        '0912205332',
                        '0912205333',
                        '0912205334',
                        '0912205335',
                        '0912205336',
                        '0913000000',
                        '0913301000',
                        '0913301101',
                        '0913301102',
                        '0913301103',
                        '0913301111',
                        '0913301112',
                        '0913301113',
                        '0913302000',
                        '0913302121',
                        '0913302122',
                        '0913303000',
                        '0913303211',
                        '0913303213',
                        "0913303220",
                        "0913304171",
                        "0913304172",
                        "0913304173",
                        "0913304174",
                        "0913305231",
                        "0913305232",
                        "0913305240",
                        "0913305250",
                        "0913305260",
                        "0913305270",
                        "0914401281",
                        "0914401282",
                        "0914401283", # Maunulanpuisto ongelma
                        "0914402341",
                        "0914403351",
                        "0914403352",
                        "0914403354",
                        "0914404284",
                        "0914404285",
                        "0914404287",
                        "0914405342",
                        "0914405353",
                        "0915501361",
                        "0915501362",
                        "0915501363",
                        "0915501364",
                        "0915501383",
                        "0915501386",
                        "0915502370",
                        "0915503381",
                        "0915503382",
                        "0915503384",
                        "0915503385",
                        "0915503391",
                        "0915503392",
                        "0915504401",
                        "0915504403",
                        "0915505402",
                        "0915505411",
                        "0915505412",
                        "0915505413",
                        "0915505415",
                        "0915506414",
                        "0916601190",
                        "0916601420",
                        "0916602431",
                        "0916602432",
                        "0916602433",
                        "0916602434",
                        "0916602440",
                        "0916603480",
                        "0916603491",
                        "0916603492",
                        "0916603493",
                        "0916603494",
                        "0916603495",
                        "0916603510",
                        "0917701451", # Itäsaaret ja Villinki jossain
                        "0917701452",
                        "0917701453",
                        "0917701455",
                        "0917701456",
                        "0917701457",
                        "0917702454",
                        "0917703471",
                        "0917703472",
                        "0917703473",
                        "0917703474",
                        "0917703475",
                        "0917704541",
                        "0917704542",
                        "0917704543",
                        "0917704544",
                        "0917704545",
                        "0917704546",
                        "0917704547",
                        "0917704548", # Mustavuori ongelma
                        "0918801550",
                        "0918801560",
                        "0918801570",
                        "0918801580",
                        "0918801591",
                        "0918801592"), # Muut
               "Kvintiilien määrittelyperuste"=c("OK"),
               "Tuloluokka"=c("ALL"),
               "Tiedot"=c("ekv_kt_mean"),
               "Vuosi"=c("2022"))

# Haetaan data ja muutetaan tietokehikkoon.

url <- c("https://stat.hel.fi:443/api/v1/fi/Aluesarjat/tul/astul/alu_astul_011y.px")

data <- pxweb_get(url,
                  query = kysely)

tulot <- as.data.frame(data,
                       column.name.type = "text",
                       variable.value.type = "text")

# Tarkemmin datasta ja muuttujista.

# px_data_comments <- pxweb_data_comments(data)
# px_data_comments_df <- as.data.frame(px_data_comments)

# Sitaatti.

# pxweb_cite(px_data)
```


```{r include=FALSE}
# Poistetaan epäolennaiset muuttujat.

tulot <- tulot %>%
  select(-c(2:4))
```
