---
title: "PX-Web API, osa 6"
author: "Henri Linnanketo"
date: "2024-10-01"
output:
  html_document: default
  word_document: default
editor_options: 
  chunk_output_type: inline
---

```{r}
# Tässä tiedostossa parsitaan yhteen PxWebista ladatut tiedot.

# Ladataan paketit.

library(dplyr)
library(tidyr)
library(stringr)

# Yhdistetään äsken ladatut tietokehikot uudeksi aineistoksi.
# Poimitaan ensin muuttujat, jotka otetaan mukaan uuteen tietokehikkoon.

tietokehikko_1 <- kielet[, c(1:2, 6:8)]
tietokehikko_2 <- korkeastikoulutetut[, c(1, 3:4)]
tietokehikko_3 <- työttömät[, c(1, 3)]
tietokehikko_4 <- työvoima[, c(1, 4:5)]
tietokehikko_5 <- pääas_toiminta[, c(1, 4:6)]

# Yhdistetään muuttujat uudeksi aineistoksi.

helsinki_147 <- Reduce(function(x, y) merge(x,
                                            y,
                                        by = "Alue"),
                   list(tietokehikko_1,
                        tietokehikko_2,
                        tietokehikko_3,
                        tietokehikko_4,
                        tietokehikko_5))

helsinki_147$Alue <- as.factor(helsinki_147$Alue)

# Yhdistetään tulomuuttuja alueen nimen perusteella.

helsinki_147 <- merge(helsinki_147,
                  tulot[, c("Alue", "Kulutusyksikkökohtaisten käyttötulojen keskiarvo")], 
                  by = "Alue", all.x = TRUE)

# Tietokehikossa on aluksi 153 havaintoa, joista 7 on ylimääräistä.
# Otetaan ensin pois entiset Sörnäisen, Ruskeasuon, Hermannin ja Lauttasaaren osa-alueet. Poistetaan myös Muut-alue.

helsinki_147 <- helsinki_147 %>%
  filter(!grepl("Ent\\.", `Alue`))

helsinki_147 <- helsinki_147 %>%
  filter(!grepl("Muut", `Alue`))

# Poistetaan haluttaessa myös Helsingin keskimääräisiä arvoja kuvaava rivi.
# Nyt kehikossa on 147 havaintoa.

helsinki_147 <- helsinki_147 %>%
  filter(!grepl("Helsinki", `Alue`))

# Putsataan vielä osa-alueen nimi numeroista ja tehdään uusi tunnusmuuttuja.

helsinki_147$Alue <- gsub("^\\d+\\s+",
                          "",
                          helsinki_147$Alue)

helsinki_147 <- helsinki_147 %>%
  mutate(Tunnus = str_extract(Alue,
                            "^\\d{2,3}"))

helsinki_147 <- helsinki_147 %>% 
  mutate(Tunnus = str_pad(Tunnus,
         width = 3,
         side = "left",
         pad = "0"))

helsinki_147$Alue <- gsub("^\\d+\\s+",
                          "",
                          helsinki_147$Alue)

# Järjestellään nimet ja muutetaan järjestystä.

helsinki_147 <- helsinki_147 %>%
  select(Alue,
         Tunnus,
         Yhteensä,
         "Kulutusyksikkökohtaisten käyttötulojen keskiarvo",
         everything())

helsinki_147 <- helsinki_147 %>% 
  rename(
    alue = 1,
    tunnus = 2,
    väestö = 3,
    tulot = 4,
    suomenkieliset = 5,
    ruotsinkieliset = 6,
    vieraskieliset = 7,
    ylempi_kork = 8,
    perusaste = 9,
    työttömyys = 10,
    työvoima = 11,
    työvoiman_ulkop = 12,
    alle_15 = 13,
    opiskelijat = 14,
    eläkeläiset = 15) %>% 
  arrange(alue)
```


# Tallennus

```{r}
# Tallennetaan csv-tiedostoksi.

write.csv(helsinki_147,
          file = "./helsinki_147.csv",
          fileEncoding = "UTF-8")
```
