---
title: "Analyysi, osa 1"
output: html_document
date: "2025-01-27"
editor_options: 
  chunk_output_type: inline
---

Tässä tiedostossa muuttujien esittelyä ja korrelaatioita.

# Osa 1: Alkutoimenpiteet

```{r include=FALSE}
library(psych)
library(sf)
library(openxlsx)
library(sostieteidentaulukointityylit)
library(scales)
library(broom)
library(tidyverse)
library(corrplot)

options(scipen = 999)

# Ladataan helsinki-kehikko.

helsinki <- read.csv("/Users/henri/Library/CloudStorage/OneDrive-UniversityofHelsinki/Helsingin yliopisto/Maisteriseminaari/Aineisto/helsinki.csv",
                     header = TRUE)[, -1]

helsinki <- helsinki %>%
  mutate_at(vars(hyöty,
                 väestö,
                 tulot,
                 suomenkieliset,
                 ruotsinkieliset,
                 vieraskieliset,
                 ylempi_kork,
                 perusaste,
                 työttömyys,
                 alle_15,
                 opiskelijat,
                 eläkeläiset),
            as.numeric) %>% 
  mutate_at(vars(tunnus),
            as.factor) %>% 
  mutate_at(vars(alue),
            as.character)

# Tehdään muutama lisämuuttuja.

helsinki <- helsinki %>% 
  mutate(hyöty_desiili = ntile(hyöty, 10)) %>% 
  mutate(koulutus_desiili = ntile(ylempi_kork, 10)) %>% 
  mutate(työttömyys_desiili = ntile(työttömyys, 10))

# Laitetaan jemmaan OmaStadi-värejä, joita hyödynnetään visualisoinneissa.

OS_beige <- rgb(253, 243, 191, maxColorValue = 255)
OS_harmaa <- rgb(102, 102, 102, maxColorValue = 255)
OS_kelt <- rgb(248, 234, 136, maxColorValue = 255)
OS_kulta <- rgb(244, 199, 76, maxColorValue = 255)
OS_sininen <- rgb(234, 234, 251, maxColorValue = 255)
```


# Osa 2: Muuttujien tarkastelu

```{r}
# Jatkuvat muuttujat eli tutkimusasetelman viisi muuttujaa (1+4).

muuttujat <- helsinki %>% 
  select(hyöty,
         tulot,
         ylempi_kork,
         vieraskieliset,
         työttömyys) %>% 
  psych::describe() %>%
  as_tibble() %>% 
  mutate(vars = case_match(vars,
                           1 ~ "Hyöty",
                           2 ~ "Kotitalouden tulot (€)",
                           3 ~ "Ylempi korkeakoulutus (%)",
                           4 ~ "Vieraskielisten osuus (%)",
                           5 ~ "Työttömyysaste (%)")) %>%
  select("vars", "n", "mean", "median", "sd", "min", "max") %>%
  mutate_if(is.numeric, round, digits = 0)

# Tulostetaan valittuja tunnuslukuja.

print(muuttujat)

# Tallennetaan muuttujia kuvaava taulukko Exceliin.

#write.xlsx(muuttujat, file = "muuttujat.xlxs", rowNames = TRUE)
```


# Osa 3: Muuttujien visualisointi

```{r}
# Hyötymuuttujan jakauma.

ggplot(helsinki, aes(x = hyöty)) + # OK graafi
  geom_histogram(aes(y = ..density..),
                 bins = 20,
                 fill = OS_kulta,
                 color = "beige") +
  geom_density(color = OS_harmaa,
               linewidth = 1.5) +
  ggtitle(NULL) +
  xlab("Hyöty") +
  ylab(NULL) +
  theme_classic() +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line.y = element_blank()) +  # Removes the left y-axis line
  scale_x_continuous(labels = label_number(big.mark = " ")) +
  scale_y_continuous(expand = expansion(mult = c(0)))


#ggsave("histogrammi.png", width = 6, height = 4, dpi = 600)  # Leveys määritelty hyväksi
                     
```


# Osa 4: Korrelaatiot

```{r}
# Tarkastellaan vielä muuttujien välisiä korrelaatioita ja luodaan korrelaatiomatriisi.
# Suodatetaan ensin muuttujat.

helsinki <- helsinki %>% 
  select(hyöty,
         tulot,
         ylempi_kork,
         vieraskieliset,
         työttömyys)

b_korrelaatiot <- helsinki %>%
  select(1:5) %>%
  cor(use='pairwise.complete.obs')

# Lasketaan p-arvot korrelaatioille.

b_korrelaatiot_p <- helsinki %>%
  select(1:5) %>%
  cor.mtest()

# Tehdään kuva korrelaatioista, jotka ovat tilastollisesti merkitseviä (sig.level).

# Kuvaa tallentaessa voi width- ja height-arvoina käyttää arvoja 850 ja 660.
# (Export -> Save as Image. Tiedostomuotona korkealaatuista kuvaa varten voi käyttää muotoa EPS.)

 corrplot::corrplot(b_korrelaatiot,
                   method="square",
                   order = "AOE",
                   type="lower", 
                   addCoef.col = "black",
                   tl.col="black",
                   tl.srt = 45,
                   diag=FALSE, 
                   cl.pos = "n",
                   number.cex = 0.70,
                   p.mat = b_korrelaatiot_p$p,
                   sig.level = 0.05,
                   insig = "blank")

#ggsave("korrelaatio.png", width = 8, height = 6, dpi = 300)  # Leveys määritelty hyväksi

# Korrelaatiomatriisin luominen ja tallentaminen exceliin. 
# (Lähde: http://www.sthda.com/english/wiki/elegant-correlation-table-using-xtable-r-package).

# Tehdään ensin funktio.

library(Hmisc)

corstars <-function(x, method=c("pearson", "spearman")){
    #Compute correlation matrix
    require(Hmisc)
    x <- as.matrix(x)
    correlation_matrix<-rcorr(x, type=method[1])
    R <- correlation_matrix$r # Matrix of correlation coeficients
    p <- correlation_matrix$P # Matrix of p-value 
    
    ## Define notions for significance levels; spacing is important.
    mystars <- ifelse(p < .001, "*** ", ifelse(p < .01, "**  ", ifelse(p < .05, "*   ", "    ")))
    
    ## trunctuate the correlation matrix to two decimal
    R <- format(round(cbind(rep(-1.11, ncol(x)), R), 2))[,-1]
    
    ## build a new matrix that includes the correlations with their apropriate stars
    Rnew <- matrix(paste(R, mystars, sep=""), ncol=ncol(x))
    diag(Rnew) <- paste(diag(R), " ", sep="")
    rownames(Rnew) <- colnames(x)
    colnames(Rnew) <- paste(colnames(x), "", sep="")
    Rnew <- as.matrix(Rnew)
      Rnew[upper.tri(Rnew, diag = TRUE)] <- ""
      Rnew <- as.data.frame(Rnew)
    Rnew <- cbind(Rnew[1:length(Rnew)-1])
}

# Edellä esitetyn funktion käyttäminen muuttujiin.

b_korrelaatiomatriisi <- helsinki %>%
  select(1:5) %>%
  corstars(method = "pearson")

print(b_korrelaatiomatriisi)

# Korrelaatiomatriisin tallennus Exceliin openxlsx-paketin avulla.

#write.xlsx(b_korrelaatiomatriisi, file = "korrelaatiot.xlxs", rowNames = TRUE)
```

