---
title: "Kartta-analyysi"
author: "Henri Linnanketo"
date: "2025-03-15"
output:
  html_document: default
  word_document: default
editor_options: 
  chunk_output_type: inline
---

# Alkutoimenpiteet

```{r message=FALSE, warning=FALSE}
library(psych)
library(sf)
library(scales)
library(broom)
library(tidyverse)
library(corrplot)
library(helsinki)
library(viridis)
library(leaflet)

options(scipen = 999)

# Ladataan helsinki-kehikko.

helsinki <- read.csv("/Users/henri/Library/CloudStorage/OneDrive-UniversityofHelsinki/Helsingin yliopisto/Maisteriseminaari/Aineisto/helsinki.csv",
                     header = TRUE)[, -1]

helsinki <- helsinki %>%
  mutate(hyöty_desiili = ntile(hyöty, 10)) %>% 
  select(1:3, hyöty_desiili, everything()) %>% 
  mutate_at(vars(hyöty,
                 väestö,
                 tulot,
                 suomenkieliset,
                 ruotsinkieliset,
                 vieraskieliset,
                 ylempi_kork,
                 perusaste,
                 työttömyys,
                 alle_15,
                 opiskelijat,
                 eläkeläiset),
            as.numeric) %>% 
  mutate_at(vars(tunnus,
                 hyöty_desiili),
            as.factor) %>% 
  mutate_at(vars(alue),
            as.character)
```


# Osa-alueiden hakeminen helsinki-paketista.

```{r message=FALSE, warning=FALSE, include=FALSE}
helsinki_kartta <- get_city_map(city = "helsinki",
                         level = "pienalue")

# Pidetään vain muutamat muuttujat.

helsinki_kartta <- helsinki_kartta %>% 
  select(8, 7, 11) %>% 
  arrange(nimi) %>% 
  rename(tunnus = pien,
         alue = nimi) %>% 
  mutate(tunnus = sub("^0+", "", tunnus)) %>% 
  mutate(tunnus = as.factor(as.character(tunnus)))

# Tuodaan helsinki-kehikosta hyödyt ja varmistetaan, että mukana on vain samat alueet.

helsinki_kartta <- helsinki_kartta %>%
  semi_join(helsinki, by = c("alue", "tunnus")) %>% 
  left_join(helsinki %>%
              select(tunnus,
                     hyöty,
                     hyöty_desiili),
            by = "tunnus") %>% 
  select(1:2, 4:5, everything())

# Muuttujien tyypit.

helsinki_kartta <- helsinki_kartta %>%
  mutate_at(vars(hyöty),
            as.numeric) %>% 
  mutate_at(vars(tunnus,
                 hyöty_desiili),
            as.factor) %>% 
  mutate_at(vars(alue),
            as.character)
```


# Kartta, osa 1: Karkea osa-alueellinen jako

```{r echo=FALSE}
library(sf)

tietokehikko <- st_as_sf(helsinki_kartta)

plot(tietokehikko$geom)

ggplot(tietokehikko) +
  geom_sf() +  # Plot the geometry (if you want to show the spatial features)
  geom_sf_text(aes(label = alue), 
               size = 3,
               color = "black",  # Color of the text labels
               check_overlap = TRUE) +  # Avoid overlapping labels
  theme_minimal()  # Clean theme

ggplot() +
  geom_sf(data = tietokehikko,
          aes(fill = hyöty_desiili),
          alpha = 0.5) +  # Taustavärin vahvuus
  geom_sf_text(data = tietokehikko,
               aes(label = alue), 
               size = 3,
               color = "black", # Tekstin väri
               check_overlap = TRUE) +  # Vältetään tekstien limittäminen
  scale_fill_viridis_d(option = "viridis") +
  theme_minimal()  # Clean theme
```


# Kartta, osa 2: Kartta HRTT-matriisin ruudukoilla

```{r echo=FALSE, message=FALSE, warning=FALSE}
input_url <- "https://kartta.hsy.fi/geoserver/wfs"
feature_of_interest <- "taustakartat_ja_aluejaot:seutukartta_kunta_2021"

# Ladataan Helsingin alueen rajat, jotka suodatetaan aineistosta kuntakoodilla 091.

rajat <- get_feature(base.url = input_url, typename = feature_of_interest)

rajat <- rajat %>% 
  filter(kunta == "091") %>% 
  slice(1)

# Avataan matka-aikamatriisi ja suodatetaan kaupungin rajojen perusteella Helsingin sisälle jäävät ruudukot.

polygonit <- st_read("/Users/henri/Documents/Helsinki_Travel_Time_Matrix_2023_grid.gpkg",
                      layer = "Helsinki_Travel_Time_Matrix_2023_grid")

st_crs(polygonit)
st_crs(rajat)

polygonit <- st_transform(polygonit, st_crs(rajat))
rajat_geom <- st_geometry(rajat)

ruudukot_helsinki <- polygonit[st_within(polygonit,
                                         rajat_geom,
                                         sparse = FALSE)[, 1], ]

# Yhdistetään ruudukkokehikkoon kymmenluokkainen hyötymuuttuja, jolla voidaan värittää matriisi eri väreillä. 

ruudukot_helsinki <- st_join(ruudukot_helsinki, 
                             helsinki_kartta[, "hyöty_desiili"],
                             left = TRUE)
```


# Kartta, osa 3: Lopulta matriisin visualisointi

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Ensimmäinen vaihtoehto

ggplot(data = ruudukot_helsinki) +
  geom_sf(aes(fill = hyöty_desiili)) + 
  scale_fill_viridis_d(option = "D",
                       alpha = 1,
                       begin = 0.5,
                       na.value = "white",
                       na.translate = TRUE,
                       name = "Teoreettinen hyöty",
                       labels = c("alin kymmenys",
                                  2:9,
                                  "ylin kymmenys",
                                  "ei tietoa")) +
  theme_void() +
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    panel.border = element_blank()) +
  labs(
    title = NULL,
    fill = "Teoreettinen hyöty") +
  guides(fill = guide_legend(title = "Teoreettinen hyöty"))


# Pienennetään legendaa.
# Tämä versio, jota käytetty gradussa.

ggplot(data = ruudukot_helsinki) +
  geom_sf(aes(fill = hyöty_desiili)) + 
  scale_fill_viridis_d(option = "D",
                       alpha = 1,
                       begin = 0.5,
                       na.value = "black",
                       na.translate = TRUE,
                       name = "Teoreettinen hyöty",
                       labels = c("alin kymmenys",
                                  2:9,
                                  "ylin kymmenys",
                                  "ei tietoa")) +
  theme_void() +
  theme(
    legend.key.size = unit(0.4, "cm"),  # Smaller legend keys
    legend.text = element_text(size = 6),  # Smaller text
    legend.title = element_text(size = 8),  # Smaller title
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    panel.border = element_blank()) +
  labs(
    title = NULL,
    fill = "Teoreettinen hyöty") +
  guides(fill = guide_legend(title = "Teoreettinen hyöty"))


# Vielä vanha versio.

ggplot(data = ruudukot_helsinki) +
  geom_sf(aes(fill = hyöty_desiili)) +  # Pohjakarttana polygonit, jotka täytetään faktorimuuttujan arvoilla
  scale_fill_viridis_d(option = "viridis",
                       alpha = 1,
                       begin = 0.5) + 
  theme_void() +
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    panel.border = element_blank()) +
  labs(
    title = NULL,
    fill = "Teoreettinen hyöty")
```


```{r eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
# Tallennus kuvaksi.
# HUOM! Kuva kannattaa rajata Wordissa. (Tuplaklikkaus kuvaan, sitten rajaa.)

ggsave("kuva6.png", 
       device = "png",
       width = 4,
       height = 5,
       units = "in",
       dpi = 600,
       bg = "white")
```























